### ISSUE TITLE
Entity backups should be removed

### ISSUE THREAD

**Issue by Kolyunya** [homelleon/yapuroshik#1]
Entity backups (e.g. `src/AppBundle/Entity/Article.php~`) should be removed from the repository. A corresponding line should be added to the `.gitignore` file.

**Comment by homelleon** [comment]
I need time to think about it.

**Comment by homelleon** [comment]
Fix that in commit:
https://github.com/homelleon/yapuroshik/commit/7012226b9e613e00dd86ff8220803017e69248f1
Thank you!
