### ISSUE TITLE
Link URLs should be generated dynamically

### ISSUE THREAD

**Issue by Kolyunya** [homelleon/yapuroshik#2]
Link URLs should be generated dynamically [via route names](http://symfony.com/doc/current/templating.html#linking-to-pages).

```twig
<a href="/news/{{ article.getID() }}">
```

should read as

```twig
<a href="{{ path("news_view", {id: article.id}) }}">
```

P.S. Route name should be configured for that to work.

**Comment by homelleon** [comment]
Thanks, mate! It will be changed after next commit.
