### ISSUE TITLE
Show a portion of articles on the main page

### ISSUE THREAD

**Issue by Kolyunya** [homelleon/yapuroshik#3]
Currently [all articles](https://github.com/homelleon/yapuroshik/blob/master/src/AppBundle/Controller/DefaultController.php#L22) available in the database are shown on the main page. It's probably a good idea to show just a portion of them (e.g. latest 10) otherwise a lot of memory would be consumed and page load time would be very high.

**Comment by homelleon** [comment]
Solved by comment:
 https://github.com/homelleon/yapuroshik/commit/4146535193389f1553388073619fd66a678b1bc0
thank you for your comments.

**Comment by Kolyunya** [comment]
Great job, mate!
